LR: 3e-4
NUM_ENVS: 2048
NUM_STEPS: 10
TOTAL_TIMESTEPS: 5e7
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 32
ENT_COEF: 0.0
NUM_UPDATES: 0
MINIBATCH_SIZE: 0
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: tanh
CRITIC_ACTIVATION: relu6
ENV_NAME: hopper
ANNEAL_LR: False
SPARSITY: 0
NORMALIZED_WEIGHTS: 0
NORMALIZE_ENV: True
DEBUG: True
ACTIVATION_FUNCTIONS: relu6, elu, gelu, swish, hardswish, softplus, tanh