LR: 5e-3
NUM_ENVS: 64
NUM_STEPS: 128
TOTAL_TIMESTEPS: 1e7
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 8
ENT_COEF: 0.01
NUM_UPDATES: 0
MINIBATCH_SIZE: 0
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: tanh
CRITIC_ACTIVATION: tanh
ENV_NAME: SpaceInvaders-MinAtar
ANNEAL_LR: True
SPARSITY: 0
NORMALIZED_WEIGHTS: 0
ACTIVATION_FUNCTIONS: relu6, elu, gelu, swish, hardswish, softplus, tanh
