LR: 5e-04
NUM_ENVS: 16
NUM_STEPS: 32
TOTAL_TIMESTEPS: 200000
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
ENT_COEF: 0
NUM_UPDATES: 0
MINIBATCH_SIZE: 0
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
VF_COEF: 0.5
MAX_GRAD_NORM: 1.0
ACTIVATION: tanh
CRITIC_ACTIVATION: tanh
ENV_NAME: FourRooms-misc
ANNEAL_LR: True
SPARSITY: 0
NORMALIZED_WEIGHTS: 0
ACTIVATION_FUNCTIONS: relu6, elu, gelu, swish, hardswish, softplus, tanh
ACTIVATION_LIST: tanh, tanh, tanh, tanh
LAYER: False